{
 "title": "Cassandra metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "show tag values from system with key = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Max Thread Pool Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cassandra_ThreadPools",
     "select": [
      [
       { "params": [ "MaxPoolSize_Value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Compacted Data (Bytes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "compacted_data",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cassandra_Compaction",
     "select": [
      [
       { "params": [ "BytesCompacted_Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Waiting on Commit Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$host-waiting-on-commit-count",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cassandra_CommitLog",
     "select": [
      [
       { "params": [ "WaitingOnCommit_Count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Client Read Write Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$host-client_read_write_latency",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cassandra_ClientRequest",
     "select": [
      [
       { "params": [ "Latency_DurationUnit" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Client Failed Request Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "alias": "$host-failed_requests",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cassandra_ClientRequest",
     "select": [
      [
       { "params": [ "Failures_MeanRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "All Memtable Live Data Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "$host-MemTable_live_data_size",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cassandra_ColumnFamily",
     "select": [
      [
       { "params": [ "AllMemtablesLiveDataSize_Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Disk Space Used by all Columns",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "$host-TotalDiskSpaceUsedCount",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cassandra_ColumnFamily",
     "select": [
      [
       { "params": [ "TotalDiskSpaceUsed_Count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of Connected Clients",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cassandra_Client",
     "select": [
      [
       { "params": [ "connectedNativeClients_Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}